"""Frozen paired-logit gate for reasoning-specific OPSD teacher signal."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path

import pyarrow.parquet as pq
import torch
import torch.nn.functional as F

from pretraining.fresh_lejepa.fresh_lejepa_train import FreshHyperparameters
from postraining.core import (
    encode_prompt,
    load_posttraining_tokenizer,
    parse_numeric_answer,
)
from postraining.math_prompt import (
    answer_fence_prompt,
    require_answer_fence_prompt_schema,
)
from postraining.model_io import load_model
from postraining.opsd.data import TEACHER_PROMPT_SCHEMA, build_teacher_prompt
from postraining.opsd.manifest import validate_final_answer_manifest
from postraining.opsd.prepare_dapo import file_sha256
from postraining.opsd.schemas import OPSD_PROMPT_SCHEMA
from postraining.opsd.teacher_uplift import (
    TEACHER_UPLIFT_SCHEMA,
    atomic_json,
    repeated_ngram_fraction,
    terminal_loop,
)
from postraining.prepare_sft_traces import INSTRUCTION_SUFFIX_ANSWER


TEACHER_LOGIT_GATE_SCHEMA = "opsd_frozen_paired_teacher_logit_gate/v2"
SELF_RATIONALIZED_TRANSITION = (
    "\n\nThe attempted worked solution above was generated by the frozen "
    "teacher from privileged answer information. Use its useful derivation "
    "as context, but independently solve the original problem again and "
    "correct any mistakes."
    f"{INSTRUCTION_SUFFIX_ANSWER}"
)
REGIONS = ("prethink", "think_q1", "think_q2", "think_q3", "think_q4", "answer")
SCORE_FIELDS = (
    "logp_question",
    "logp_direct",
    "logp_correct",
    "logp_permuted",
    "correct_minus_permuted",
    "correct_minus_direct",
    "correct_minus_question",
    "permuted_minus_question",
    "update_direct",
    "update_correct",
    "update_permuted",
    "update_correct_minus_permuted",
    "update_correct_minus_direct",
    "kl_correct_question",
    "kl_permuted_question",
    "kl_direct_question",
    "clipped_loss_direct",
    "clipped_loss_correct",
    "clipped_loss_permuted",
    "clipped_entry_fraction_direct",
    "clipped_entry_fraction_correct",
    "clipped_entry_fraction_permuted",
    "gradient_norm_direct",
    "gradient_norm_correct",
    "gradient_norm_permuted",
    "gradient_cosine",
    "gradient_delta_norm_correct_permuted",
    "gradient_delta_fraction_correct_permuted",
    "gradient_delta_norm_correct_direct",
    "gradient_delta_fraction_correct_direct",
)

TEACHER_ARMS = ("direct", "correct", "permuted")


def panel_stats(values: list[float], seed: int, resamples: int = 20_000) -> dict:
    if not values:
        raise ValueError("panel statistics require values")
    tensor = torch.tensor(values, dtype=torch.float64)
    generator = torch.Generator().manual_seed(seed)
    count = tensor.numel()
    indices = torch.randint(0, count, (resamples, count), generator=generator)
    bootstrap = tensor[indices].mean(1)
    signs = (
        torch.randint(0, 2, (resamples, count), generator=generator, dtype=torch.float64)
        * 2
        - 1
    )
    mean = float(tensor.mean())
    permuted = (signs * tensor).mean(1)
    extreme = int((permuted.abs() >= abs(mean) - 1e-12).sum())
    return {
        "prompts": count,
        "mean": mean,
        "bootstrap_ci_low": float(torch.quantile(bootstrap, 0.025)),
        "bootstrap_ci_high": float(torch.quantile(bootstrap, 0.975)),
        "permutation_p": (extreme + 1) / (resamples + 1),
    }


def auc(correct: list[float], incorrect: list[float]) -> float:
    if not correct or not incorrect:
        raise ValueError("AUC requires both classes")
    wins = 0.0
    for positive in correct:
        for negative in incorrect:
            wins += float(positive > negative) + 0.5 * float(positive == negative)
    return wins / (len(correct) * len(incorrect))


def clipped_observed_update(
    student_log_probs: torch.Tensor,
    teacher_log_probs: torch.Tensor,
    labels: torch.Tensor,
    *,
    temperature: float,
    pointwise_clip: float,
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Exact descent update on each observed logit under pointwise-clipped KL."""
    student_probs = student_log_probs.exp()
    teacher_probs = teacher_log_probs.exp()
    contributions = teacher_probs * (teacher_log_probs - student_log_probs)
    active = contributions <= pointwise_clip
    active_teacher = active * teacher_probs
    mass = active_teacher.sum(-1)
    gradient = (student_probs * mass[:, None] - active_teacher) / temperature
    observed = -gradient.gather(1, labels[:, None]).squeeze(1)
    gradient_norm = torch.linalg.vector_norm(gradient, dim=-1)
    return observed, {
        "forward_kl": contributions.sum(-1),
        "clipped_loss": contributions.clamp(max=pointwise_clip).sum(-1),
        "clipped_entry_fraction": (~active).float().mean(-1),
        "gradient": gradient,
        "gradient_norm": gradient_norm,
    }


@torch.no_grad()
def response_features_varied_batch(
    model,
    prompts: list[list[int]],
    responses: list[list[int]],
    device,
):
    """Batch causal response features for independently sized prompts.

    Sequences are right-padded only after their final response prefix token,
    so padding cannot affect any selected causal feature. This lets the
    answer-conditioned self-rationalization gate retain one distinct teacher
    context per sampled trajectory without falling back to batch size one.
    """
    if len(prompts) != len(responses) or not prompts:
        raise ValueError("prompts and responses must be equally sized and nonempty")
    if any(not prompt for prompt in prompts) or any(not response for response in responses):
        raise ValueError("prompts and responses must contain nonempty token lists")
    sequence_lengths = [
        len(prompt) + len(response) - 1
        for prompt, response in zip(prompts, responses, strict=True)
    ]
    width = max(sequence_lengths)
    batch = torch.full(
        (len(responses), width),
        int(prompts[0][0]),
        dtype=torch.long,
        device=device,
    )
    for row, (prompt_ids, response) in enumerate(
        zip(prompts, responses, strict=True)
    ):
        prompt = torch.tensor(prompt_ids, dtype=torch.long, device=device)
        sequence = torch.cat(
            (prompt, torch.tensor(response[:-1], dtype=torch.long, device=device))
        )
        batch[row, : sequence.numel()] = sequence
    with torch.autocast(
        device_type=device.type,
        dtype=torch.bfloat16,
        enabled=device.type == "cuda",
    ):
        token_latent = model.embed_tokens(batch)
        belief = model.temporal_belief_from_token_latent(token_latent)
        features = torch.cat((token_latent, belief), dim=-1)
    selected = [
        features[row, len(prompt) - 1 : len(prompt) - 1 + len(response)]
        for row, (prompt, response) in enumerate(
            zip(prompts, responses, strict=True)
        )
    ]
    return torch.cat(selected), [len(response) for response in responses]


@torch.no_grad()
def response_features_batch(model, prompt_ids: list[int], responses: list[list[int]], device):
    return response_features_varied_batch(
        model, [prompt_ids] * len(responses), responses, device
    )


@torch.no_grad()
def score_varied_prompt_responses(
    model,
    prompt_ids_by_arm: dict[str, list[list[int]]],
    responses: list[list[int]],
    device,
    *,
    temperature: float,
    pointwise_clip: float,
    logit_chunk_tokens: int,
) -> list[dict[str, list[float]]]:
    expected_arms = {"question", *TEACHER_ARMS}
    if set(prompt_ids_by_arm) != expected_arms:
        raise ValueError(f"scoring requires exactly {sorted(expected_arms)}")
    if any(len(prompts) != len(responses) for prompts in prompt_ids_by_arm.values()):
        raise ValueError("every scoring arm needs one prompt per response")
    features = {
        arm: response_features_varied_batch(model, prompts, responses, device)[0]
        for arm, prompts in prompt_ids_by_arm.items()
    }
    labels = torch.tensor(
        [token for response in responses for token in response],
        dtype=torch.long,
        device=device,
    )
    flat = {field: [] for field in SCORE_FIELDS}
    total = labels.numel()
    for start in range(0, total, logit_chunk_tokens):
        stop = min(start + logit_chunk_tokens, total)
        log_probs = {}
        for arm in ("question", *TEACHER_ARMS):
            with torch.autocast(
                device_type=device.type,
                dtype=torch.bfloat16,
                enabled=device.type == "cuda",
            ):
                logits = model.logits_from_features(features[arm][start:stop])
            log_probs[arm] = F.log_softmax(logits.float() / temperature, dim=-1)
        chunk_labels = labels[start:stop]
        observed = {
            arm: values.gather(1, chunk_labels[:, None]).squeeze(1)
            for arm, values in log_probs.items()
        }
        updates = {}
        diagnostics = {}
        for arm in TEACHER_ARMS:
            updates[arm], diagnostics[arm] = clipped_observed_update(
                log_probs["question"],
                log_probs[arm],
                chunk_labels,
                temperature=temperature,
                pointwise_clip=pointwise_clip,
            )
        correct = diagnostics["correct"]
        permuted = diagnostics["permuted"]
        direct = diagnostics["direct"]
        cosine = F.cosine_similarity(
            correct["gradient"], permuted["gradient"], dim=-1, eps=1e-12
        )
        delta_cp = torch.linalg.vector_norm(
            correct["gradient"] - permuted["gradient"], dim=-1
        )
        delta_cd = torch.linalg.vector_norm(
            correct["gradient"] - direct["gradient"], dim=-1
        )
        values = {
            "logp_question": observed["question"],
            "logp_direct": observed["direct"],
            "logp_correct": observed["correct"],
            "logp_permuted": observed["permuted"],
            "correct_minus_permuted": observed["correct"] - observed["permuted"],
            "correct_minus_direct": observed["correct"] - observed["direct"],
            "correct_minus_question": observed["correct"] - observed["question"],
            "permuted_minus_question": observed["permuted"] - observed["question"],
            "update_direct": updates["direct"],
            "update_correct": updates["correct"],
            "update_permuted": updates["permuted"],
            "update_correct_minus_permuted": (
                updates["correct"] - updates["permuted"]
            ),
            "update_correct_minus_direct": (
                updates["correct"] - updates["direct"]
            ),
            "kl_correct_question": correct["forward_kl"],
            "kl_permuted_question": permuted["forward_kl"],
            "kl_direct_question": direct["forward_kl"],
            "clipped_loss_direct": direct["clipped_loss"],
            "clipped_loss_correct": correct["clipped_loss"],
            "clipped_loss_permuted": permuted["clipped_loss"],
            "clipped_entry_fraction_direct": direct["clipped_entry_fraction"],
            "clipped_entry_fraction_correct": correct["clipped_entry_fraction"],
            "clipped_entry_fraction_permuted": permuted["clipped_entry_fraction"],
            "gradient_norm_direct": direct["gradient_norm"],
            "gradient_norm_correct": correct["gradient_norm"],
            "gradient_norm_permuted": permuted["gradient_norm"],
            "gradient_cosine": cosine,
            "gradient_delta_norm_correct_permuted": delta_cp,
            "gradient_delta_fraction_correct_permuted": (
                delta_cp / correct["gradient_norm"].clamp_min(1e-12)
            ),
            "gradient_delta_norm_correct_direct": delta_cd,
            "gradient_delta_fraction_correct_direct": (
                delta_cd / correct["gradient_norm"].clamp_min(1e-12)
            ),
        }
        for field, tensor in values.items():
            flat[field].extend(float(value) for value in tensor.cpu())
    output = []
    cursor = 0
    for response in responses:
        stop = cursor + len(response)
        output.append({field: flat[field][cursor:stop] for field in SCORE_FIELDS})
        cursor = stop
    return output


@torch.no_grad()
def score_prompt_responses(
    model,
    prompt_ids_by_arm: dict[str, list[int]],
    responses: list[list[int]],
    device,
    *,
    temperature: float,
    pointwise_clip: float,
    logit_chunk_tokens: int,
) -> list[dict[str, list[float]]]:
    if set(prompt_ids_by_arm) == {"question", "correct", "permuted"}:
        prompt_ids_by_arm = {
            **prompt_ids_by_arm,
            "direct": prompt_ids_by_arm["correct"],
        }
    varied = {
        arm: [prompt] * len(responses)
        for arm, prompt in prompt_ids_by_arm.items()
    }
    return score_varied_prompt_responses(
        model,
        varied,
        responses,
        device,
        temperature=temperature,
        pointwise_clip=pointwise_clip,
        logit_chunk_tokens=logit_chunk_tokens,
    )


def extract_fixed_think_prefix(
    attempt: dict,
    *,
    think_ids: tuple[int, int],
    forbidden_ids: set[int],
    rationale_tokens: int,
    max_repeated_4gram_fraction: float,
) -> tuple[list[int] | None, str | None]:
    """Extract one arm-blind fixed-length rationale without answer tokens."""
    emitted = [int(token) for token in attempt["emitted_token_ids"]]
    if not attempt.get("terminated"):
        return None, "unterminated"
    if not attempt.get("structural_format_ok"):
        return None, "invalid_response_contract"
    if terminal_loop(emitted):
        return None, "terminal_loop"
    try:
        start = emitted.index(think_ids[0]) + 1
        stop = emitted.index(think_ids[1], start)
    except ValueError:
        return None, "missing_think_fence"
    reasoning = emitted[start:stop]
    if len(reasoning) < rationale_tokens:
        return None, "short_think"
    prefix = reasoning[:rationale_tokens]
    if any(token in forbidden_ids for token in prefix):
        return None, "embedded_special_token"
    if repeated_ngram_fraction(prefix) > max_repeated_4gram_fraction:
        return None, "repetitive_think"
    return prefix, None


def build_self_rationalized_prompt_arms(
    *,
    correct_base: list[int],
    permuted_base: list[int],
    question_rationale: list[int],
    correct_rationale: list[int],
    permuted_rationale: list[int],
    transition_ids: list[int],
    response_tokens: int,
    context_tokens: int,
) -> dict[str, list[int]]:
    """Build exact-position-matched teacher contexts for one fixed response.

    ``direct`` is the incremental-effect control: it has the verified answer
    in the same base prompt as ``correct``, but receives an answer-unconditioned
    self-rationale sampled from the question-only policy. The rationale arms
    therefore differ only in their fixed-length generated reasoning tokens.
    """
    lengths = {
        len(question_rationale),
        len(correct_rationale),
        len(permuted_rationale),
    }
    if len(correct_base) != len(permuted_base):
        raise ValueError("correct and permuted bases must be position matched")
    if len(lengths) != 1:
        raise ValueError("all rationale arms must use one fixed token budget")
    prompts = {
        "direct": correct_base + question_rationale + transition_ids,
        "correct": correct_base + correct_rationale + transition_ids,
        "permuted": permuted_base + permuted_rationale + transition_ids,
    }
    if len({len(prompt) for prompt in prompts.values()}) != 1:
        raise AssertionError("teacher response positions are not matched")
    if any(
        len(prompt) + response_tokens - 1 > context_tokens
        for prompt in prompts.values()
    ):
        raise ValueError("self-rationalized scoring context would overflow")
    return prompts


def subsequence_mask(tokens: list[int], sequences: set[tuple[int, ...]], halo: int = 2):
    masked = [False] * len(tokens)
    for sequence in sequences:
        if not sequence:
            continue
        for start in range(len(tokens) - len(sequence) + 1):
            if tuple(tokens[start : start + len(sequence)]) == sequence:
                left = max(0, start - halo)
                right = min(len(tokens), start + len(sequence) + halo)
                masked[left:right] = [True] * (right - left)
    return masked


def numeric_equivalent_mask(
    tokens: list[int],
    tokenizer,
    targets: set,
    *,
    max_window: int = 12,
    halo: int = 2,
    decode_cache: dict[int, str] | None = None,
):
    masked = [False] * len(tokens)
    if not targets:
        return masked
    cache = {} if decode_cache is None else decode_cache
    pieces = []
    for token in tokens:
        if token not in cache:
            cache[token] = tokenizer.decode([token])
        pieces.append(cache[token])
    for start in range(len(tokens)):
        text = ""
        for stop in range(start + 1, min(len(tokens), start + max_window) + 1):
            text += pieces[stop - 1]
            candidates = {
                text.strip(),
                text.strip(" \n\t;:,.!?()[]"),
            }
            if not any(parse_numeric_answer(candidate) in targets for candidate in candidates):
                continue
            left = max(0, start - halo)
            right = min(len(tokens), stop + halo)
            masked[left:right] = [True] * (right - left)
    return masked


def response_regions(
    tokens,
    think_ids,
    answer_ids,
    answer_sequences,
    *,
    tokenizer=None,
    numeric_targets=(),
    decode_cache=None,
):
    regions = {name: [] for name in REGIONS}
    try:
        think_open = tokens.index(think_ids[0])
        think_close = tokens.index(think_ids[1], think_open + 1)
        answer_open = tokens.index(answer_ids[0], think_close + 1)
        answer_close = tokens.index(answer_ids[1], answer_open + 1)
    except ValueError:
        return regions
    think = list(range(think_open + 1, think_close))
    for quartile in range(4):
        left = len(think) * quartile // 4
        right = len(think) * (quartile + 1) // 4
        regions[f"think_q{quartile + 1}"] = think[left:right]
    prethink = think[: len(think) * 3 // 4]
    masked = subsequence_mask(tokens, answer_sequences, halo=2)
    if tokenizer is not None:
        numeric_masked = numeric_equivalent_mask(
            tokens,
            tokenizer,
            set(numeric_targets),
            halo=2,
            decode_cache=decode_cache,
        )
        masked = [left or right for left, right in zip(masked, numeric_masked)]
    regions["prethink"] = [index for index in prethink if not masked[index]]
    regions["answer"] = list(range(answer_open + 1, answer_close))
    return regions


def mean_region(scores: dict[str, list[float]], indices: list[int]) -> dict[str, float]:
    if not indices:
        return {}
    return {
        field: sum(scores[field][index] for index in indices) / len(indices)
        for field in SCORE_FIELDS
    }


def answer_sequences(tokenizer, *answers: str) -> set[tuple[int, ...]]:
    sequences = set()
    for answer in answers:
        for text in (answer, " " + answer, "\n" + answer):
            encoded = tuple(tokenizer.encode(text))
            if encoded:
                sequences.add(encoded)
    return sequences


def load_bound_attempt_panel(
    path: str | Path,
    arm: str,
    rollout_result: dict,
    rows: list[dict],
    prompt_for_row,
    parser,
) -> list[dict]:
    """Load one immutable, complete arm panel bound by uplift-result hashes."""
    artifact = Path(path)
    expected_sha256 = (rollout_result.get("attempts_sha256") or {}).get(arm)
    if expected_sha256 is None:
        parser.error(f"rollout result does not bind its {arm} attempts")
    if file_sha256(artifact) != expected_sha256:
        parser.error(f"{arm} attempts do not match rollout result bytes")
    payload = json.loads(artifact.read_text())
    if payload.get("schema") != TEACHER_UPLIFT_SCHEMA:
        parser.error(f"{arm} attempts use a different uplift schema")
    if payload.get("arm") != arm:
        parser.error(f"expected {arm} attempts, got {payload.get('arm')!r}")
    attempts = payload.get("attempts")
    if not isinstance(attempts, list):
        parser.error(f"{arm} attempt payload is not a list")
    samples = int(rollout_result["args"]["samples"])
    if len(attempts) != len(rows) * samples:
        parser.error(f"{arm} artifact does not contain the full fixed panel")
    observed_grid = {
        (int(attempt["problem_index"]), int(attempt["sample_index"]))
        for attempt in attempts
    }
    expected_grid = {
        (problem_index, sample_index)
        for problem_index in range(len(rows))
        for sample_index in range(samples)
    }
    if len(observed_grid) != len(attempts) or observed_grid != expected_grid:
        parser.error(f"{arm} attempts are not one complete unique sample grid")
    for attempt in attempts:
        problem_index = int(attempt["problem_index"])
        if str(attempt["dataset_index"]) != str(rows[problem_index]["example_id"]):
            parser.error(f"{arm} dataset attribution does not match the gate")
        if attempt["prompt"] != prompt_for_row(rows[problem_index]):
            parser.error(f"{arm} prompt does not match its canonical context")
    return attempts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True)
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--gate-data", required=True)
    parser.add_argument("--data-manifest", required=True)
    parser.add_argument("--rollout-results", required=True)
    parser.add_argument("--rollout-attempts", required=True)
    parser.add_argument("--correct-rationalizations")
    parser.add_argument("--permuted-rationalizations")
    parser.add_argument("--rationale-tokens", type=int, default=96)
    parser.add_argument("--rationale-sample-offset", type=int, default=1)
    parser.add_argument("--max-rationale-repeated-4gram", type=float, default=0.35)
    parser.add_argument(
        "--panel-role",
        choices=("development", "authorization"),
        default="development",
    )
    parser.add_argument("--temperature", type=float, default=1.1)
    parser.add_argument("--pointwise-kl-clip", type=float, default=0.05)
    parser.add_argument("--logit-chunk-tokens", type=int, default=256)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    rationalization_paths = (
        args.correct_rationalizations,
        args.permuted_rationalizations,
    )
    if (rationalization_paths[0] is None) != (rationalization_paths[1] is None):
        parser.error("correct and permuted rationalizations must be supplied together")
    if rationalization_paths[0] is None:
        parser.error("the v2 gate requires frozen correct and permuted rationalizations")
    if args.rationale_tokens < 1:
        parser.error("rationale token budget must be positive")
    if args.rationale_sample_offset < 1:
        parser.error("rationale sample offset must be positive")
    if not 0 <= args.max_rationale_repeated_4gram <= 1:
        parser.error("rationale repetition threshold must be in [0, 1]")
    output = Path("postraining/runs") / args.name / "teacher_logit_gate"
    if output.exists():
        parser.error(f"refusing to overwrite logit gate {output}")

    manifest_path = Path(args.data_manifest)
    manifest = json.loads(manifest_path.read_text())
    gate_path = Path(args.gate_data)
    checkpoint_path = Path(args.checkpoint)
    if file_sha256(gate_path) != manifest.get("gate_sha256"):
        parser.error("gate bytes do not match manifest")
    try:
        validate_final_answer_manifest(manifest)
    except ValueError as error:
        parser.error(str(error))
    if manifest.get("teacher_prompt_schema") != TEACHER_PROMPT_SCHEMA:
        parser.error("manifest uses a different teacher prompt schema")
    if manifest.get("opsd_prompt_schema") != OPSD_PROMPT_SCHEMA:
        parser.error("manifest uses a different OPSD prompt schema")
    rows = pq.read_table(gate_path).to_pylist()
    if len(rows) != manifest.get("gate_rows"):
        parser.error("gate row count does not match manifest")
    if any(
        row["teacher_prompt_tokens"] != row["permuted_teacher_prompt_tokens"]
        for row in rows
    ):
        parser.error("teacher control response positions are not matched")

    rollout_result = json.loads(Path(args.rollout_results).read_text())
    if rollout_result.get("schema") != TEACHER_UPLIFT_SCHEMA:
        parser.error("rollout result uses a different teacher-uplift schema")
    if rollout_result.get("checkpoint_sha256") != file_sha256(checkpoint_path):
        parser.error("rollouts use different checkpoint bytes")
    if rollout_result.get("gate_sha256") != manifest.get("gate_sha256"):
        parser.error("rollouts use different gate bytes")
    attempts = load_bound_attempt_panel(
        args.rollout_attempts,
        "question_only",
        rollout_result,
        rows,
        lambda row: answer_fence_prompt(str(row["problem"])),
        parser,
    )
    rationalization_attempts = None
    if args.correct_rationalizations is not None:
        rationalization_attempts = {
            "correct": load_bound_attempt_panel(
                args.correct_rationalizations,
                "correct_answer",
                rollout_result,
                rows,
                lambda row: build_teacher_prompt(
                    str(row["problem"]),
                    str(row["solution"]),
                    "final_answer",
                    INSTRUCTION_SUFFIX_ANSWER,
                ),
                parser,
            ),
            "permuted": load_bound_attempt_panel(
                args.permuted_rationalizations,
                "permuted_answer",
                rollout_result,
                rows,
                lambda row: build_teacher_prompt(
                    str(row["problem"]),
                    str(row["permuted_solution"]),
                    "final_answer",
                    INSTRUCTION_SUFFIX_ANSWER,
                ),
                parser,
            ),
        }

    payload = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    sft = payload.get("sft") or {}
    require_answer_fence_prompt_schema(
        sft, answer_fence=True, source="OPSD teacher-logit checkpoint"
    )
    tokenizer = load_posttraining_tokenizer(
        payload["architecture"],
        FreshHyperparameters.tokenizer_path,
        think_tokens=True,
        answer_tokens=True,
        tokenizer_provenance=payload["model_config"].get(
            "tokenizer_provenance"
        ),
    )
    context_tokens = int(payload.get("train_seq_len", 1024))
    tokenizer_path = Path(FreshHyperparameters.tokenizer_path)
    device = torch.device("cuda")
    model = load_model(checkpoint_path, device, payload=payload)
    del payload
    model.eval()
    stop_ids = {
        token for token in (tokenizer.eos_id(), tokenizer.bos_id()) if token >= 0
    }
    think_ids = (tokenizer.think_open_id, tokenizer.think_close_id)
    answer_ids = (tokenizer.answer_open_id, tokenizer.answer_close_id)

    samples_per_prompt = int(rollout_result["args"]["samples"])
    rationale_offset = args.rationale_sample_offset % samples_per_prompt
    if rationale_offset == 0:
        parser.error("rationale sample offset must differ from the scored response")
    attempts_by_prompt = defaultdict(list)
    for attempt in attempts:
        attempts_by_prompt[int(attempt["problem_index"])].append(attempt)
    assert rationalization_attempts is not None
    attempt_index = {
        "question": {
            (int(attempt["problem_index"]), int(attempt["sample_index"])): attempt
            for attempt in attempts
        },
        **{
            arm: {
                (int(attempt["problem_index"]), int(attempt["sample_index"])): attempt
                for attempt in panel
            }
            for arm, panel in rationalization_attempts.items()
        },
    }
    scored_attempts = []
    rationale_rejections: Counter[str] = Counter()
    decode_cache: dict[int, str] = {}
    transition_ids = tokenizer.encode(SELF_RATIONALIZED_TRANSITION)
    if not transition_ids:
        raise RuntimeError("self-rationalized transition encoded to no tokens")
    forbidden_rationale_ids = {*stop_ids, *think_ids, *answer_ids}
    for problem_index, row in enumerate(rows):
        prompt_attempts = sorted(
            attempts_by_prompt[problem_index], key=lambda item: item["sample_index"]
        )
        responses: list[list[int]] = []
        retained_attempts: list[dict] = []
        prompt_ids_by_arm = {
            arm: [] for arm in ("question", *TEACHER_ARMS)
        }
        rationale_metadata = []
        problem = str(row["problem"])
        question_ids = encode_prompt(tokenizer, answer_fence_prompt(problem))
        correct_base = encode_prompt(
            tokenizer,
            build_teacher_prompt(
                problem,
                str(row["solution"]),
                "final_answer",
                INSTRUCTION_SUFFIX_ANSWER,
            ),
        )
        permuted_base = encode_prompt(
            tokenizer,
            build_teacher_prompt(
                problem,
                str(row["permuted_solution"]),
                "final_answer",
                INSTRUCTION_SUFFIX_ANSWER,
            ),
        )
        if len(correct_base) != len(permuted_base):
            raise AssertionError("teacher prompt position matching changed at runtime")
        for attempt in prompt_attempts:
            tokens = [int(token) for token in attempt["emitted_token_ids"]]
            cut = next(
                (index for index, token in enumerate(tokens) if token in stop_ids),
                None,
            )
            response = tokens if cut is None else tokens[:cut]
            if not response:
                continue
            response_sample = int(attempt["sample_index"])
            rationale_sample = (response_sample + rationale_offset) % samples_per_prompt
            rationale_prefixes = {}
            pair_rejected = False
            for arm in ("question", "correct", "permuted"):
                source_attempt = attempt_index[arm][
                    (problem_index, rationale_sample)
                ]
                rationale, reason = extract_fixed_think_prefix(
                    source_attempt,
                    think_ids=think_ids,
                    forbidden_ids=forbidden_rationale_ids,
                    rationale_tokens=args.rationale_tokens,
                    max_repeated_4gram_fraction=(
                        args.max_rationale_repeated_4gram
                    ),
                )
                if reason is not None:
                    rationale_rejections[f"{arm}:{reason}"] += 1
                    pair_rejected = True
                else:
                    assert rationale is not None
                    rationale_prefixes[arm] = rationale
            if pair_rejected:
                rationale_rejections["symmetric_pair_rejected"] += 1
                continue
            teacher_prompts = build_self_rationalized_prompt_arms(
                correct_base=correct_base,
                permuted_base=permuted_base,
                question_rationale=rationale_prefixes["question"],
                correct_rationale=rationale_prefixes["correct"],
                permuted_rationale=rationale_prefixes["permuted"],
                transition_ids=transition_ids,
                response_tokens=len(response),
                context_tokens=context_tokens,
            )
            responses.append(response)
            retained_attempts.append(attempt)
            prompt_ids_by_arm["question"].append(question_ids)
            for arm in TEACHER_ARMS:
                prompt_ids_by_arm[arm].append(teacher_prompts[arm])
            rationale_metadata.append(
                {
                    "source_sample_index": rationale_sample,
                    "tokens_per_arm": args.rationale_tokens,
                    "teacher_prompt_tokens": len(teacher_prompts["correct"]),
                }
            )
        if not responses:
            continue
        scores = score_varied_prompt_responses(
            model,
            prompt_ids_by_arm,
            responses,
            device,
            temperature=args.temperature,
            pointwise_clip=args.pointwise_kl_clip,
            logit_chunk_tokens=args.logit_chunk_tokens,
        )
        sequences = answer_sequences(
            tokenizer, str(row["solution"]), str(row["permuted_solution"])
        )
        numeric_targets = {
            value
            for value in (
                parse_numeric_answer(str(row["solution"])),
                parse_numeric_answer(str(row["permuted_solution"])),
            )
            if value is not None
        }
        for attempt, response, token_scores, rationale in zip(
            retained_attempts,
            responses,
            scores,
            rationale_metadata,
            strict=True,
        ):
            regions = response_regions(
                response,
                think_ids,
                answer_ids,
                sequences,
                tokenizer=tokenizer,
                numeric_targets=numeric_targets,
                decode_cache=decode_cache,
            )
            scored_attempts.append(
                {
                    "problem_index": problem_index,
                    "sample_index": int(attempt["sample_index"]),
                    "contract_correct": bool(attempt["contract_correct"]),
                    "structural_format_ok": bool(attempt["structural_format_ok"]),
                    "terminated": bool(attempt["terminated"]),
                    "response_tokens": len(response),
                    "rationale": rationale,
                    "regions": {
                        region: {
                            "tokens": len(indices),
                            "metrics": mean_region(token_scores, indices),
                        }
                        for region, indices in regions.items()
                    },
                }
            )
        print(f"scored prompt {problem_index + 1}/{len(rows)}", flush=True)

    valid = [
        attempt
        for attempt in scored_attempts
        if attempt["terminated"]
        and attempt["structural_format_ok"]
        and attempt["regions"]["prethink"]["tokens"] > 0
    ]
    valid_by_prompt = defaultdict(list)
    for attempt in valid:
        valid_by_prompt[attempt["problem_index"]].append(attempt)
    mixed = {
        index: panel
        for index, panel in valid_by_prompt.items()
        if any(item["contract_correct"] for item in panel)
        and any(not item["contract_correct"] for item in panel)
    }

    def metric(item, region, field):
        return item["regions"][region]["metrics"][field]

    auc_deltas_cd = []
    auc_deltas_cp = []
    update_contrasts_cp = []
    update_contrasts_cd = []
    gradient_fractions_cp = []
    gradient_fractions_cd = []
    for panel in mixed.values():
        correct = [item for item in panel if item["contract_correct"]]
        incorrect = [item for item in panel if not item["contract_correct"]]
        aucs = {
            arm: auc(
                [metric(item, "prethink", f"logp_{arm}") for item in correct],
                [metric(item, "prethink", f"logp_{arm}") for item in incorrect],
            )
            for arm in ("question", *TEACHER_ARMS)
        }
        auc_deltas_cd.append(aucs["correct"] - aucs["direct"])
        auc_deltas_cp.append(aucs["correct"] - aucs["permuted"])
        update_contrasts_cp.append(
            sum(metric(item, "prethink", "update_correct_minus_permuted") for item in correct)
            / len(correct)
            - sum(metric(item, "prethink", "update_correct_minus_permuted") for item in incorrect)
            / len(incorrect)
        )
        update_contrasts_cd.append(
            sum(metric(item, "prethink", "update_correct_minus_direct") for item in correct)
            / len(correct)
            - sum(metric(item, "prethink", "update_correct_minus_direct") for item in incorrect)
            / len(incorrect)
        )
        gradient_fractions_cp.append(
            sum(
                metric(
                    item,
                    "prethink",
                    "gradient_delta_fraction_correct_permuted",
                )
                for item in panel
            )
            / len(panel)
        )
        gradient_fractions_cd.append(
            sum(
                metric(
                    item,
                    "prethink",
                    "gradient_delta_fraction_correct_direct",
                )
                for item in panel
            )
            / len(panel)
        )

    correct_panels = [
        [item for item in panel if item["contract_correct"]]
        for panel in valid_by_prompt.values()
        if any(item["contract_correct"] for item in panel)
    ]
    answer_advantages = [
        sum(metric(item, "answer", "correct_minus_permuted") for item in panel)
        / len(panel)
        for panel in correct_panels
        if all(item["regions"]["answer"]["tokens"] > 0 for item in panel)
    ]
    primary = {
        "auc_correct_minus_direct": panel_stats(auc_deltas_cd, args.seed + 1)
        if auc_deltas_cd
        else None,
        "auc_correct_minus_permuted": panel_stats(auc_deltas_cp, args.seed + 2)
        if auc_deltas_cp
        else None,
        "clipped_update_correctness_contrast_vs_direct": panel_stats(
            update_contrasts_cd, args.seed + 3
        )
        if update_contrasts_cd
        else None,
        "clipped_update_correctness_contrast_vs_permuted": panel_stats(
            update_contrasts_cp, args.seed + 4
        )
        if update_contrasts_cp
        else None,
        "causal_gradient_fraction_vs_direct": panel_stats(
            gradient_fractions_cd, args.seed + 5
        )
        if gradient_fractions_cd
        else None,
        "causal_gradient_fraction_vs_permuted": panel_stats(
            gradient_fractions_cp, args.seed + 6
        )
        if gradient_fractions_cp
        else None,
        "correct_answer_logp_advantage": panel_stats(
            answer_advantages, args.seed + 7
        )
        if answer_advantages
        else None,
    }
    sensitivity = {}
    for region in REGIONS:
        region_panels = [
            panel
            for panel in mixed.values()
            if all(item["regions"][region]["tokens"] > 0 for item in panel)
        ]
        deltas_cd = []
        deltas_cp = []
        for panel in region_panels:
            correct = [item for item in panel if item["contract_correct"]]
            incorrect = [item for item in panel if not item["contract_correct"]]
            arm_auc = {
                arm: auc(
                    [metric(item, region, f"logp_{arm}") for item in correct],
                    [metric(item, region, f"logp_{arm}") for item in incorrect],
                )
                for arm in ("question", *TEACHER_ARMS)
            }
            deltas_cd.append(arm_auc["correct"] - arm_auc["direct"])
            deltas_cp.append(arm_auc["correct"] - arm_auc["permuted"])
        sensitivity[region] = {
            "auc_correct_minus_direct": (
                panel_stats(deltas_cd, args.seed + 100 + len(sensitivity) * 2)
                if deltas_cd
                else None
            ),
            "auc_correct_minus_permuted": (
                panel_stats(deltas_cp, args.seed + 101 + len(sensitivity) * 2)
                if deltas_cp
                else None
            ),
        }
    diagnostic_means = {
        region: {
            field: (
                sum(
                    metric(item, region, field)
                    for item in valid
                    if item["regions"][region]["tokens"] > 0
                )
                / sum(
                    item["regions"][region]["tokens"] > 0 for item in valid
                )
            )
            for field in SCORE_FIELDS
        }
        for region in REGIONS
    }
    correct_count = sum(item["contract_correct"] for item in valid)
    incorrect_count = len(valid) - correct_count
    structural_rate = sum(
        bool(item["terminated"] and item["structural_format_ok"])
        for item in attempts
    ) / len(attempts)
    rationale_retention = len(scored_attempts) / len(attempts)
    prethink_tokens = sum(item["regions"]["prethink"]["tokens"] for item in valid)
    first_three_quartile_tokens = sum(
        sum(item["regions"][f"think_q{q}"]["tokens"] for q in (1, 2, 3))
        for item in valid
    )
    retained_fraction = prethink_tokens / max(first_three_quartile_tokens, 1)
    power_reasons = []
    if len(mixed) < 30:
        power_reasons.append("fewer than 30 mixed prompts")
    if correct_count < 40:
        power_reasons.append("fewer than 40 correct structured trajectories")
    if incorrect_count < 200:
        power_reasons.append("fewer than 200 incorrect structured trajectories")
    if structural_rate < 0.90:
        power_reasons.append("common structural validity below 0.90")
    if rationale_retention < 0.50:
        power_reasons.append("fixed self-rationale retention below 0.50")
    if retained_fraction < 0.50:
        power_reasons.append("answer-masked prethink retention below 0.50")
    reasons = []
    if power_reasons:
        decision = "underpowered"
        reasons = power_reasons
    else:
        for name in ("auc_correct_minus_direct", "auc_correct_minus_permuted"):
            stats = primary[name]
            if stats["mean"] < 0.05:
                reasons.append(f"{name} below +0.05")
            if stats["bootstrap_ci_low"] <= 0:
                reasons.append(f"{name} bootstrap lower bound not positive")
            if stats["permutation_p"] >= 0.05:
                reasons.append(f"{name} permutation p is not below 0.05")
        for name in (
            "clipped_update_correctness_contrast_vs_direct",
            "clipped_update_correctness_contrast_vs_permuted",
        ):
            update = primary[name]
            if update["mean"] <= 0 or update["bootstrap_ci_low"] <= 0:
                reasons.append(f"{name} is not robustly positive")
        for name in (
            "causal_gradient_fraction_vs_direct",
            "causal_gradient_fraction_vs_permuted",
        ):
            gradient = primary[name]
            if gradient["mean"] < 0.10:
                reasons.append(f"{name} below 0.10")
            if gradient["bootstrap_ci_low"] < 0.05:
                reasons.append(f"{name} bootstrap lower bound below 0.05")
        answer = primary["correct_answer_logp_advantage"]
        if answer is None or answer["mean"] <= 0 or answer["bootstrap_ci_low"] <= 0:
            reasons.append("correct teacher lacks answer-token sanity advantage")
        if reasons:
            decision = "fail"
        else:
            decision = "pass" if args.panel_role == "authorization" else "promising"

    result = {
        "schema": TEACHER_LOGIT_GATE_SCHEMA,
        "decision": decision,
        "reasons": reasons,
        "power": {
            "mixed_prompts": len(mixed),
            "correct_structured_trajectories": correct_count,
            "incorrect_structured_trajectories": incorrect_count,
            "common_structural_validity": structural_rate,
            "fixed_self_rationale_retention": rationale_retention,
            "answer_masked_prethink_retained_fraction": retained_fraction,
        },
        "primary": primary,
        "sensitivity": sensitivity,
        "diagnostic_means": diagnostic_means,
        "checkpoint": str(checkpoint_path),
        "checkpoint_sha256": file_sha256(checkpoint_path),
        "tokenizer": str(tokenizer_path),
        "tokenizer_sha256": file_sha256(tokenizer_path),
        "gate_data": str(gate_path),
        "gate_sha256": manifest["gate_sha256"],
        "data_manifest_sha256": file_sha256(manifest_path),
        "opsd_prompt_schema": OPSD_PROMPT_SCHEMA,
        "conditioning": {
            "method": "answer_only_frozen_self_rationalization_extension",
            "paper_algorithm_reproduction": False,
            "student_response_source": "question_only_frozen_sft_rollout",
            "direct_control": (
                "correct_answer_plus_independent_question_only_self_rationale"
            ),
            "rationale_source": "frozen_sft_rollout_no_external_trace",
            "rationale_rejections": dict(sorted(rationale_rejections.items())),
            "transition_sha256": hashlib.sha256(
                SELF_RATIONALIZED_TRANSITION.encode()
            ).hexdigest(),
            "transition_token_ids_sha256": hashlib.sha256(
                json.dumps(transition_ids, separators=(",", ":")).encode()
            ).hexdigest(),
        },
        "input_artifacts": {
            "rollout_results_sha256": file_sha256(Path(args.rollout_results)),
            "question_responses_sha256": file_sha256(Path(args.rollout_attempts)),
            "correct_rationalizations_sha256": file_sha256(
                Path(args.correct_rationalizations)
            ),
            "permuted_rationalizations_sha256": file_sha256(
                Path(args.permuted_rationalizations)
            ),
        },
        "args": vars(args),
    }
    output.mkdir(parents=True)
    attempt_metrics_path = output / "attempt_metrics.json"
    atomic_json(
        {"schema": TEACHER_LOGIT_GATE_SCHEMA, "attempts": scored_attempts},
        attempt_metrics_path,
    )
    result["attempt_metrics_sha256"] = file_sha256(attempt_metrics_path)
    atomic_json(result, output / "results.json")
    print(json.dumps({"decision": decision, "reasons": reasons, "power": result["power"], "primary": primary}, indent=2))
    raise SystemExit(0 if decision in {"pass", "promising"} else 2)


if __name__ == "__main__":
    main()
